/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MedicalRecord } from "./MedicalRecord";
export * as factories from "./factories";
export { MedicalRecord__factory } from "./factories/MedicalRecord__factory";
