/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MedicalRecord {
  export type InvoiceStruct = {
    id: BigNumberish;
    patient: AddressLike;
    doctor: AddressLike;
    amount: BigNumberish;
    recordId: BigNumberish;
    timestamp: BigNumberish;
    invoiceNumber: string;
    hash: string;
    verified: boolean;
    verifier: AddressLike;
  };

  export type InvoiceStructOutput = [
    id: bigint,
    patient: string,
    doctor: string,
    amount: bigint,
    recordId: bigint,
    timestamp: bigint,
    invoiceNumber: string,
    hash: string,
    verified: boolean,
    verifier: string
  ] & {
    id: bigint;
    patient: string;
    doctor: string;
    amount: bigint;
    recordId: bigint;
    timestamp: bigint;
    invoiceNumber: string;
    hash: string;
    verified: boolean;
    verifier: string;
  };

  export type RecordStruct = {
    id: BigNumberish;
    doctor: AddressLike;
    patient: AddressLike;
    patientName: string;
    consultationTime: BigNumberish;
    chiefComplaint: string;
    presentIllness: string;
    pastHistory: string;
    examination: string;
    diagnosis: string;
    treatment: string;
    timestamp: BigNumberish;
    hash: string;
  };

  export type RecordStructOutput = [
    id: bigint,
    doctor: string,
    patient: string,
    patientName: string,
    consultationTime: bigint,
    chiefComplaint: string,
    presentIllness: string,
    pastHistory: string,
    examination: string,
    diagnosis: string,
    treatment: string,
    timestamp: bigint,
    hash: string
  ] & {
    id: bigint;
    doctor: string;
    patient: string;
    patientName: string;
    consultationTime: bigint;
    chiefComplaint: string;
    presentIllness: string;
    pastHistory: string;
    examination: string;
    diagnosis: string;
    treatment: string;
    timestamp: bigint;
    hash: string;
  };

  export type UserStruct = {
    userAddress: AddressLike;
    role: BigNumberish;
    name: string;
    idNumber: string;
    registered: boolean;
  };

  export type UserStructOutput = [
    userAddress: string,
    role: bigint,
    name: string,
    idNumber: string,
    registered: boolean
  ] & {
    userAddress: string;
    role: bigint;
    name: string;
    idNumber: string;
    registered: boolean;
  };
}

export interface MedicalRecordInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createInvoice"
      | "createRecord"
      | "doctorRecords"
      | "getDoctorRecords"
      | "getInvoice"
      | "getInvoiceCount"
      | "getPatientInvoices"
      | "getPatientRecords"
      | "getPendingInvoices"
      | "getRecord"
      | "getUser"
      | "getVerifiedInvoices"
      | "invoiceCount"
      | "invoices"
      | "isUserRegistered"
      | "patientInvoices"
      | "patientRecords"
      | "recordCount"
      | "records"
      | "registerUser"
      | "users"
      | "verifyInvoice"
      | "verifyInvoices"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InvoiceCreated"
      | "InvoiceVerified"
      | "RecordCreated"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [AddressLike, BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createRecord",
    values: [
      AddressLike,
      string,
      BigNumberish,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "doctorRecords",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDoctorRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoiceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientInvoices",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingInvoices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedInvoices",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invoiceCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invoices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientInvoices",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "patientRecords",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "verifyInvoice",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyInvoices",
    values: [BigNumberish[], boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doctorRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDoctorRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInvoice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvoiceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientInvoices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingInvoices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedInvoices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invoiceCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invoices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientInvoices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyInvoices",
    data: BytesLike
  ): Result;
}

export namespace InvoiceCreatedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    patient: AddressLike,
    amount: BigNumberish,
    invoiceNumber: string
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    patient: string,
    amount: bigint,
    invoiceNumber: string
  ];
  export interface OutputObject {
    invoiceId: bigint;
    patient: string;
    amount: bigint;
    invoiceNumber: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvoiceVerifiedEvent {
  export type InputTuple = [
    invoiceId: BigNumberish,
    verifier: AddressLike,
    verified: boolean
  ];
  export type OutputTuple = [
    invoiceId: bigint,
    verifier: string,
    verified: boolean
  ];
  export interface OutputObject {
    invoiceId: bigint;
    verifier: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecordCreatedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    doctor: AddressLike,
    patient: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    doctor: string,
    patient: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    doctor: string;
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    role: BigNumberish,
    name: string
  ];
  export type OutputTuple = [user: string, role: bigint, name: string];
  export interface OutputObject {
    user: string;
    role: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MedicalRecord extends BaseContract {
  connect(runner?: ContractRunner | null): MedicalRecord;
  waitForDeployment(): Promise<this>;

  interface: MedicalRecordInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createInvoice: TypedContractMethod<
    [
      patient: AddressLike,
      recordId: BigNumberish,
      amount: BigNumberish,
      invoiceNumber: string,
      hash: string
    ],
    [void],
    "nonpayable"
  >;

  createRecord: TypedContractMethod<
    [
      patient: AddressLike,
      patientName: string,
      consultationTime: BigNumberish,
      chiefComplaint: string,
      presentIllness: string,
      pastHistory: string,
      examination: string,
      diagnosis: string,
      treatment: string,
      hash: string
    ],
    [void],
    "nonpayable"
  >;

  doctorRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getDoctorRecords: TypedContractMethod<[], [bigint[]], "view">;

  getInvoice: TypedContractMethod<
    [invoiceId: BigNumberish],
    [MedicalRecord.InvoiceStructOutput],
    "view"
  >;

  getInvoiceCount: TypedContractMethod<[], [bigint], "view">;

  getPatientInvoices: TypedContractMethod<
    [patient: AddressLike],
    [bigint[]],
    "view"
  >;

  getPatientRecords: TypedContractMethod<
    [patient: AddressLike],
    [bigint[]],
    "view"
  >;

  getPendingInvoices: TypedContractMethod<[], [bigint[]], "view">;

  getRecord: TypedContractMethod<
    [recordId: BigNumberish],
    [MedicalRecord.RecordStructOutput],
    "view"
  >;

  getUser: TypedContractMethod<
    [userAddress: AddressLike],
    [MedicalRecord.UserStructOutput],
    "view"
  >;

  getVerifiedInvoices: TypedContractMethod<[], [bigint[]], "view">;

  invoiceCount: TypedContractMethod<[], [bigint], "view">;

  invoices: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        string
      ] & {
        id: bigint;
        patient: string;
        doctor: string;
        amount: bigint;
        recordId: bigint;
        timestamp: bigint;
        invoiceNumber: string;
        hash: string;
        verified: boolean;
        verifier: string;
      }
    ],
    "view"
  >;

  isUserRegistered: TypedContractMethod<
    [userAddress: AddressLike],
    [boolean],
    "view"
  >;

  patientInvoices: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  patientRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  recordCount: TypedContractMethod<[], [bigint], "view">;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        doctor: string;
        patient: string;
        patientName: string;
        consultationTime: bigint;
        chiefComplaint: string;
        presentIllness: string;
        pastHistory: string;
        examination: string;
        diagnosis: string;
        treatment: string;
        timestamp: bigint;
        hash: string;
      }
    ],
    "view"
  >;

  registerUser: TypedContractMethod<
    [role: BigNumberish, name: string, idNumber: string],
    [void],
    "nonpayable"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, string, boolean] & {
        userAddress: string;
        role: bigint;
        name: string;
        idNumber: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  verifyInvoice: TypedContractMethod<
    [invoiceId: BigNumberish, isValid: boolean],
    [void],
    "nonpayable"
  >;

  verifyInvoices: TypedContractMethod<
    [invoiceIds: BigNumberish[], isValid: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createInvoice"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      recordId: BigNumberish,
      amount: BigNumberish,
      invoiceNumber: string,
      hash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRecord"
  ): TypedContractMethod<
    [
      patient: AddressLike,
      patientName: string,
      consultationTime: BigNumberish,
      chiefComplaint: string,
      presentIllness: string,
      pastHistory: string,
      examination: string,
      diagnosis: string,
      treatment: string,
      hash: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "doctorRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDoctorRecords"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getInvoice"
  ): TypedContractMethod<
    [invoiceId: BigNumberish],
    [MedicalRecord.InvoiceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvoiceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPatientInvoices"
  ): TypedContractMethod<[patient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPatientRecords"
  ): TypedContractMethod<[patient: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPendingInvoices"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [MedicalRecord.RecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [userAddress: AddressLike],
    [MedicalRecord.UserStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifiedInvoices"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "invoiceCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invoices"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        string
      ] & {
        id: bigint;
        patient: string;
        doctor: string;
        amount: bigint;
        recordId: bigint;
        timestamp: bigint;
        invoiceNumber: string;
        hash: string;
        verified: boolean;
        verifier: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isUserRegistered"
  ): TypedContractMethod<[userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "patientInvoices"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "patientRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        doctor: string;
        patient: string;
        patientName: string;
        consultationTime: bigint;
        chiefComplaint: string;
        presentIllness: string;
        pastHistory: string;
        examination: string;
        diagnosis: string;
        treatment: string;
        timestamp: bigint;
        hash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [role: BigNumberish, name: string, idNumber: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, string, boolean] & {
        userAddress: string;
        role: bigint;
        name: string;
        idNumber: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyInvoice"
  ): TypedContractMethod<
    [invoiceId: BigNumberish, isValid: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyInvoices"
  ): TypedContractMethod<
    [invoiceIds: BigNumberish[], isValid: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "InvoiceCreated"
  ): TypedContractEvent<
    InvoiceCreatedEvent.InputTuple,
    InvoiceCreatedEvent.OutputTuple,
    InvoiceCreatedEvent.OutputObject
  >;
  getEvent(
    key: "InvoiceVerified"
  ): TypedContractEvent<
    InvoiceVerifiedEvent.InputTuple,
    InvoiceVerifiedEvent.OutputTuple,
    InvoiceVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RecordCreated"
  ): TypedContractEvent<
    RecordCreatedEvent.InputTuple,
    RecordCreatedEvent.OutputTuple,
    RecordCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "InvoiceCreated(uint256,address,uint256,string)": TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;
    InvoiceCreated: TypedContractEvent<
      InvoiceCreatedEvent.InputTuple,
      InvoiceCreatedEvent.OutputTuple,
      InvoiceCreatedEvent.OutputObject
    >;

    "InvoiceVerified(uint256,address,bool)": TypedContractEvent<
      InvoiceVerifiedEvent.InputTuple,
      InvoiceVerifiedEvent.OutputTuple,
      InvoiceVerifiedEvent.OutputObject
    >;
    InvoiceVerified: TypedContractEvent<
      InvoiceVerifiedEvent.InputTuple,
      InvoiceVerifiedEvent.OutputTuple,
      InvoiceVerifiedEvent.OutputObject
    >;

    "RecordCreated(uint256,address,address,uint256)": TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;
    RecordCreated: TypedContractEvent<
      RecordCreatedEvent.InputTuple,
      RecordCreatedEvent.OutputTuple,
      RecordCreatedEvent.OutputObject
    >;

    "UserRegistered(address,uint8,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
